import { OpenAPIHono } from "@hono/zod-openapi";
import { Scalar } from "@scalar/hono-api-reference";
import authRouter from "./modules/auth";

const app = new OpenAPIHono();

app.route("/auth", authRouter);

app.doc("/openapi.json", {
	openapi: "3.0.0",
	info: {
		version: "1.0.0",
		title: "ScrumBoard API",
		description: "API documentation generated by Hono and Zod",
	},
});

app.get(
	"/docs",
	Scalar({
		url: "/openapi.json",
		pageTitle: "ScrumBoard Docs",
	}),
);

export default app;
