import { OpenAPIHono } from "@hono/zod-openapi";
import { Scalar } from "@scalar/hono-api-reference";
import { cors } from "hono/cors";
import authRouter from "./modules/auth";
import type { AppEnv } from "./types";

const app = new OpenAPIHono<AppEnv>();

app.use(
	"*",
	cors({
		origin: process.env.FRONTEND_URL || "http://localhost:5173",
		allowHeaders: ["Content-Type", "Authorization"],
		allowMethods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"],
		credentials: true,
	}),
);

app.route("/auth", authRouter);

app.doc("/openapi.json", {
	openapi: "3.0.0",
	info: {
		version: "1.0.0",
		title: "ScrumBoard API",
		description: "API documentation generated by Hono and Zod",
	},
});

app.get(
	"/docs",
	Scalar({
		url: "/openapi.json",
		pageTitle: "ScrumBoard Docs",
	}),
);

export default app;
