// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
	schema: "apps/api/src/db/prisma/schema.prisma",
	migrations: {
		path: "apps/api/db/migrations",
	},
	datasource: {
		url: env("DATABASE_URL"),
	},
});
